### ISSUE TITLE
Benchmark the BLS12_381-sign server 

### ISSUE THREAD

**Issue by autholykos** [dusk-network/bls12_381-sign#19]
**Describe what you want implemented** 
A set of benchmark to establish a performance baseline for the BLS signature server

**Describe "Why" this is needed**
In order to optimize and increase performances of the BLS signature verification and creation in Node, the BLS signature server needs to scale. However, to avoid premature optimization, we need to benchmark real world usage and see if we need a concurrent/parallel strategy. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by l0k18** [comment]
After discussion and investigations I am adding Capnproto in place of Protobuf, as it focuses especially on minimizing memory allocation on the client side, which is where our biggest requirement lies. The service will operate in parallel on the service and the client will choose one or the other, as the network/rpc setup/overhead is otherwise the same for both.

**Comment by l0k18** [comment]
Not really sure if this issue actually needs anything to be done for it. Expert rust programmers should be able to advise on the most economic ways to prepare parameters and process results.
